### ISSUE TITLE
target_lock + targeted func_door

### ISSUE THREAD

**Issue by porglezomp** [itslunaranyo/copper#10]
The `target_lock` and a `func_door` that's targeted by another entity don't seem to interact correctly.

If I have the following setup:
- A `func_door`
- A button that targets it to open it
- A `target_lock` that targets the door
- A button that targets that

![image](https://user-images.githubusercontent.com/1690225/190958199-bac77090-91c5-4dd0-8186-6da8bcc4ec63.png)

In Quakespasm, the lock doesn't seem to do anything to the door. The button still opens it every time. (Note that it works perfectly fine for a door that's not targeted by anything, it opens when I get close, and closes immediately when locked, and refuses to open while locked.)

In the Quake rerelease, it's *much* worse. If I have the `target_lock` set to "Target entities start locked", I get a program error:
```
======OBJECT ERROR in door_lock:

EDICT 42:

origin        '-40.0 -168.0  24.0'
classname      target_lock
use            target_lock_use()
think          target_lock_use()
spawnflags     1.0
target         door_test
targetname     lock_door_test
Host_Error: Program error
```

If I don't have the "start locked" set, it's even worse, when toggling the lock on the door the engine hard crashes with an access violation.

Tested with Copper v1.19, Quakespasm 0.94.1, and the Quake rerelease 1.0.5224 (Jul 5 2022)

**Comment by itslunaranyo** [comment]
wasn't interacting correctly with doors that didn't have trigger_fields. 

fixed for 1.20 in 7d4e7a9
