### ISSUE TITLE
deathmatch 3 respawns

### ISSUE THREAD

**Issue by porglezomp** [itslunaranyo/copper#11]
Copper doesn't seem to implement `deathmatch 3`, which I would like to use (and which is the default in the rerelease).

If I load a map under `deathmatch 3` with `game copper`, no items respawn when picked up.
The same map behaves correctly with `deathmatch 3` + `game id1`.

**Comment by itslunaranyo** [comment]
added this for v1.20 (november of 2022) and forgot to close the issue, cool cool
