### ISSUE TITLE
Spawning monsters will stop func_flytrains from floating around

### ISSUE THREAD

**Issue by bstordeur** [itslunaranyo/copper#12]
We discussed this on Discord, but I did a bit more digging trying to see if I could find a workaround, and it turns out the problem is a bit wider than I thought.

Turns out if you have a func_flytrain in your map that is just floating around, spawning any monster into the map will stop the floating, the flytrain will become static for some reason.
Example map : 
[traintest2.txt](https://github.com/itslunaranyo/copper/files/10124879/traintest2.txt)
Left button starts the train, wait for it to reach the end of its path.
Right button spawns a puppy (don't hurt it!) but will also stop the func_flytrain from floating.

This was tested on Copper 1.20 and 1.19.
Sent a video on Discord as well.

**Comment by itslunaranyo** [comment]
I still never figured out what on earth was causing this, but func_flytrain has been rewritten entirely and doesn't do this any more, so, next version will take care of it.
