### ISSUE TITLE
target_lock unable to re-activate teleporters

### ISSUE THREAD

**Issue by A-Daya** [itslunaranyo/copper#13]
Currently building a map where teleporters start off as inactive, which are then activated afterwards.
They do start off inactive, but they cannot re-activate despite a trigger clearly triggering the target_lock:
![3](https://user-images.githubusercontent.com/28660210/211349309-b1e832de-d064-4e37-937b-11f102c8623b.png)

This is the portal system I have set up:
![1](https://user-images.githubusercontent.com/28660210/211349419-5ab9c296-34f0-49e8-870c-9e393cfcf88a.png)
![2](https://user-images.githubusercontent.com/28660210/211349422-5a432f2c-94e5-47f8-b9aa-a68c3a6538ff.png)

Is there something I'm missing or is this a bug?

**Comment by itslunaranyo** [comment]
Teleport triggers that have targetnames default to only being activated when triggered (for id1-style telebox spawners). If you want a teleporter to have a targetname but not behave like that you need to check the "not triggerable (ignore targetname)" spawnflag.
