### ISSUE TITLE
Cooperative mode: keys lost forever

### ISSUE THREAD

**Issue by Mhbuur** [itslunaranyo/copper#14]
Playing in co-op mode, if the key holder dies, the key is gone forever, and you have to restart the level or resort to no-clip etc.
Either the key itself should reapper or the key should be transferred to other players.

**Comment by itslunaranyo** [comment]
The raised key limit from 15 to 16 didn't percolate to the key transfer code, so one fewer key was being transferred and the last one lost. Fixed in b557d3e6 for next version.

**Comment by Neubulae** [comment]
Now it gives the incorrect amount of keys sometimes, under both `coop 1` and `coop 2`...
It's quite bemusing to see your friend dying and all in a sudden you get a whole whopping 16 of silver keys(plus maybe just 1 golden key or something), I have zero to none idea how that happens, let alone finding a minimal test case...
Glad that can be reproduced with one friend only?
