### ISSUE TITLE
Support for Scourge of Aramagon and Dissolution of Eternity

### ISSUE THREAD

**Issue by De-Seppe** [itslunaranyo/copper#2]
This is not a bug, but a feature request.
Are you also planning to release a Copper mod for Scourge of Aramagon and Dissolution of Eternity?

**Comment by StygianEmperor** [comment]
Yes please. I’ve been wanting to replay Armagon with a mod like this, AD, or Q1.5 Combat+.

**Comment by GregRGM** [comment]
Echoing this sentiment. 
It's a shame that we can only use this incredible gameplay mod with standalone maps and the original campaign.

**Comment by itslunaranyo** [comment]
I do not have plans to support the mission packs now, or in the future. They have some deeply flawed additions that I frankly don't feel like polishing or trying to make fun. Sorry.
