### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by MissLavender-LQ** [itslunaranyo/copper#21]
what licence is this under asking for a friend
gpl?

**Comment by itslunaranyo** [comment]
still GPLv2+, like the 1.06 progs. 

you're right of course, "everyone knows that" isn't good enough, have added LICENSE file and readme blurb

**Comment by MissLavender-LQ** [comment]
ah people were miss lead by this 

![image](https://github.com/itslunaranyo/copper/assets/51702517/ddfe3492-f9aa-4f92-88c9-8106421be8f2)


![image](https://github.com/itslunaranyo/copper/assets/51702517/870f5b28-dbb8-448e-a8f6-0ecd046c19b9)
