### ISSUE TITLE
Explobox warning with Authentic Model Improvements for Quake

### ISSUE THREAD

**Issue by strangebit** [itslunaranyo/copper#3]
Just upgraded to 1.16 and am now getting this warning on E1M1 when using [NightFright2k19/quake_authmdl](https://github.com/NightFright2k19/quake_authmdl).

Also posted this on their GitHub: NightFright2k19/quake_authmdl#4

![spasm0001](https://user-images.githubusercontent.com/11712728/124353823-bf264880-dc00-11eb-92be-145f9514fa70.jpg)

My QuakeSpasm-Spiked revision is f1cc25c0b89580fa72bab61302eb82d28449d8ec (2021-June-25).

**Comment by NightFright2k19** [comment]
b_exbox2.bsp and b_explob.bsp in the AMP are MDLs renamed to BSP. This is usually a trick tolerated by most ports.
Copper seems to use entity class SOLID_BSP which requires a .bsp format model. If non-solid class were used, .mdl format would also be possible.

**Comment by NightFright2k19** [comment]
Exploding boxes have been replaced with true BSPs. This should get rid of the warnings.

**Comment by strangebit** [comment]
Ok cool! I'll close this then.
