### ISSUE TITLE
Imprecise zoom aim

### ISSUE THREAD

**Issue by luigio** [itslunaranyo/copper#4]
When I zoom in (with F11), the aim becomes very imprecise. The hit point moves in increments of a chunk of pixels, so it is impossible to hit something between one hit point and the next. Instead, in vanilla Quake, the hit point is always at the crosshair, as it should be.

**Comment by itslunaranyo** [comment]
fixed in 12e147f, will be in next patch (1.20, no ETA)

**Comment by luigio** [comment]
Awesome!
